insert into country values('Afghanistan', 'Kabul')
insert into country values('Albania', 'Tirana')
insert into country values('India', 'New Delhi')
insert into country values ('Andorra', 'Andorra la Vella')
insert into country values ('Angola','Luanda')
insert into country values ('Antigua and Barbuda','St. Johns')
insert into country values ('Argentina','Buenos Aires')
insert into country values ('Armenia','Yerevan')
insert into country values ('Australia','Canberra')
insert into country values ('Austria','Vienna')
insert into country values ('Azerbaijan','Baku')
insert into country values ('Bahamas','Nassau')
insert into country values ('Bahrain','Manama')
insert into country values ('Bangladesh','Dhaka')
insert into country values ('Barbados','Bridgetown')
insert into country values ('Belarus','Minsk')
insert into country values ('Belgium','Brussels')
insert into country values ('Belize','Belmopan')
insert into country values ('Benis','Portonovo,Cotonou')
insert into country values ('Bhutan','Thimphu')
insert into country values ('Bolivia','La Paz and Sucre')
insert into country values ('Bosnia and Herzegovina','Sarajevo')
insert into country values ('Botswana','Gaborone')
insert into country values ('Brazil','Brasilia')
insert into country values ('Brunei','Bandar Seri Begawan')
insert into country values ('Bulgaria','Sofia')
insert into country values ('Burkina Faso','Ouagadougou')
insert into country values ('Burundi','Bujumbura')
insert into country values ('Cambodia','Phnom Penh')
insert into country values ('Cameroon','Yaounde')
insert into country values ('Canada','Ottawa')
insert into country values ('Cape Verde','Praia')
insert into country values ('Cayman Islands','George Town')
insert into country values ('Central African Republic','Bangui')
insert into country values ('Chad','N Djamena')
insert into country values ('Chile','Santiago')
insert into country values ('China','Beijing')
insert into country values ('Colombia','Bogota')
insert into country values ('Comoros','Moroni')
insert into country values ('Costa Rica','San Jose')
insert into country values ('Cote d lvoire','Yamoussoukro')
insert into country values ('Croatia','Zagreb')
insert into country values ('Cuba','Havana')
insert into country values ('Cyprus','Nicosia')
insert into country values ('Czech Republic','Prague')
insert into country values ('Democratic Republic of Congo','Kinshasa')
insert into country values ('Denmark','Copenhagen')
insert into country values ('Djibouti','Djibouti')
insert into country values ('Dominica','Roseau')
insert into country values ('Dominican Republic','Santo Domingo')
insert into country values ('East Timor','Dili')
insert into country values ('Ecuador','Quito')
insert into country values ('Egypt','Cairo')
insert into country values ('En Salvador','San Salvador')
insert into country values ('Equitorial Guinea','Malabo')
insert into country values ('Eritrea','Asmara')
insert into country values ('Estonia','Talinn')
insert into country values ('Ethiopia','Addis Ababa')
insert into country values ('Fiji','Suva')
insert into country values ('Finland','Helsinki')
insert into country values ('France','Paris')
insert into country values ('French Guiana','Cayenne')
insert into country values ('Gabon','Libreville')
insert into country values ('Georgia','Tbilisi')
insert into country values ('Germany','Berlin')
insert into country values ('Ghana','Accra')
insert into country values ('Greece','Athens')
insert into country values ('Grenada','St. George')
insert into country values ('Guatemala','Guatemala')
insert into country values ('Guinea','Conakry')
insert into country values ('Guinea-Bissau','Guyana,Georgetown')
insert into country values ('Haiti','Port-au-Prince')
insert into country values ('Honduras','Tegucigalpa')
insert into country values ('Hungary','Budapest')
insert into country values ('Iceland','Reykjavik')
insert into country values ('Indonesia','Jakarta')
insert into country values ('Iran','Tehran')
insert into country values ('Iraq','Baghdad')
insert into country values ('Israel','Jerusalem')
insert into country values ('Italy','Rome')
insert into country values ('Jamaica','Kingston,Jamaica')
insert into country values ('Japan','Tokyo')
insert into country values ('Jordan','Amman')
insert into country values ('Kazakhstan','Astana')
insert into country values ('Kenya','Nairobi')
insert into country values ('Kiribati','South Tarawa')
insert into country values ('Kuwait','Kuwait')
insert into country values ('Kyrgyzstan','Bishkek')
insert into country values ('Laos','Vientiane')
insert into country values ('Latvia','Riga')
insert into country values ('Lebanon','Beirut')
insert into country values ('Lesotho','Maseru')
insert into country values ('Liberia','Monrovia')
insert into country values ('Libya','Tripoli')
insert into country values ('Liechtenstein','Vaduz')
insert into country values ('Lithuania','Vilnius')
insert into country values ('Luxembourg','Luxembourg City')
insert into country values ('Madagascar','Antananarivo')
insert into country values ('Malawi','Lilongwe')
insert into country values ('Malaysia','Kuala Lumpur')
insert into country values ('Maldives','Male')
insert into country values ('Mali','Bamako')
insert into country values ('Malta','Valletta')
insert into country values ('Marshall Islands','Majuro')
insert into country values ('Mauritania','Nouakchott')
insert into country values ('Mauritius','Port Louis')
insert into country values ('Mexico','Mexico City')
insert into country values ('Micronesia','Palikir')
insert into country values ('Moldova','Chisinau')
insert into country values ('Monaco','Monaco')
insert into country values ('Mongolia','Ulaanbaatar')
insert into country values ('Montenegro','Podgorica')
insert into country values ('Morocco','Rabat')
insert into country values ('Mozambique','Maputo')
insert into country values ('Myanmar','Naypyidaw')
insert into country values ('Namibia','Windhoek')
insert into country values ('Nauru','Yaren')
insert into country values ('Nepal','Kathmandu')
insert into country values ('Netherlands','Amsterdam')
insert into country values ('New Zealand','Wellington')
insert into country values ('Nicargua','Managua')
insert into country values ('Niger','Niamey')
insert into country values ('Nigeria','Abuja')
insert into country values ('North Korea','Pyongyang')
insert into country values ('Norway','Oslo')
insert into country values ('Oman','Muscat')
insert into country values ('Pakistan','Islamabad')
insert into country values ('Palau','Koror')
insert into country values ('Palestine','Jerusalem')
insert into country values ('Panama','Panama City')
insert into country values ('Papua New Guinea','Port Moresby')
insert into country values ('Paraguay','Asuncion')
insert into country values ('Peru','Lima')
insert into country values ('Philippines','Manila')
insert into country values ('Poland','Warsaw')
insert into country values ('Portugal','Lisbon')
insert into country values ('Puerto Rico','San Juan')
insert into country values ('Qatar','Doha')
insert into country values ('Republic Of Ireland','Dublin')
insert into country values ('Republic of Macedonia','Skopje')
insert into country values ('Republic of the Congo','Brazzaville')
insert into country values ('Romania','Bucharest')
insert into country values ('Russia','Moscow')
insert into country values ('Rwanda','Kigali')
insert into country values ('Saint Kitts and Nevis','Basseterre')
insert into country values ('Saint Lucia','Castries')
insert into country values ('Saint Vincent and Grenadines','Kingstown')
insert into country values ('Samoa','Apia')
insert into country values ('San Marino','San Marino')
insert into country values ('Sao Tome and Principe','Sao Tome')
insert into country values ('Saudi Arabia','Riyadh')
insert into country values ('Senegal','Dakar')
insert into country values ('Serbia','Belgrade')
insert into country values ('Seychelles','Victoria')
insert into country values ('Sierra Leone','Freetown')
insert into country values ('Singapore','Singapore')
insert into country values ('Slovakia','Bratislava')
insert into country values ('Slovenia','Ljublijana')
insert into country values ('Solomon Islands','Honiara')
insert into country values ('Somalia','Mogadishu')
insert into country values ('South Africa','Pretoria')
insert into country values ('South Korea','Seoul')
insert into country values ('South Sudan','Juba')
insert into country values ('Spain','Madrid')
insert into country values ('Sri Lanka','Sri Jaywardenapura and Colombo')
insert into country values ('Sudan','Khartoum')
insert into country values ('Suriname','Paramaribo')
insert into country values ('Swaziland','Mbabane')
insert into country values ('Sweden','Stockholm')
insert into country values ('Switzerland','Bern')
insert into country values ('Syria','Damascus')
insert into country values ('Taiwan','Taipei')
insert into country values ('Tajikistan','Dushanbe')
insert into country values ('Tanzania','Dar es Salaam, Dodoma')
insert into country values ('Thailand','Bangkok')
insert into country values ('The Gambia','Banjul')
insert into country values ('Togo','Lome')
insert into country values ('Tonga','Nuku alofa')
insert into country values ('Trinidad and Tobago','Port of Spain')
insert into country values ('Tunisia','Tunis')
insert into country values ('Turkey','Ankara')
insert into country values ('Turkeministan','Asgabat')
insert into country values ('Turks and Caicos','Cockburn Town')
insert into country values ('Tuvalu','Funafuti')
insert into country values ('Uganda','Kampala')
insert into country values ('Ukraine','Kiev')
insert into country values ('United Arab Emirates','Abu Dhabi')
insert into country values ('United Kingdom','London')
insert into country values ('United States','Washington DC')
insert into country values ('Uruguay','Montevideo')
insert into country values ('Uzbekistan','Tashkent')
insert into country values ('Vanuatu','Port Vila')
insert into country values ('Vatican City','Vatican City')
insert into country values ('Venezuela','Caracas')
insert into country values ('Vietnam','Hanoi')
insert into country values ('Western Sahara','La youn')
insert into country values ('Yemen','Sanaa')
insert into country values ('Zambia','Lusaka')
insert into country values ('Zimbabwe','Harare')