insert into student values (010,'Aditi','Python')
insert into student values (020,'Alok','Java')
insert into student values (030,'Yogi','VLSI')
insert into student values (040,'Hrishi','ML')
insert into student values (050,'NA','NA')
insert into student values (060,'Krishna','NA')